singleQuote: false
tabWidth: 2
printWidth: 120
semi: true
bracketSameLine: false
bracketSpacing: true
embeddedLanguageFormatting: "auto"
arrowParens: "always"
endOfLine: "lf"
htmlWhitespaceSensitivity: "css"
trailingComma: "es5"
vueIndentScriptAndStyle: false